language: objective-c
xcode_project: PocketSocket.xcodeproj
xcode_scheme: PSAutobahnTests

before_install:
    - pip install autobahntestsuite
    
before_script:
    - wstest -m fuzzingserver & disown
    - sleep 2